/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Shams
 */
public class BookingPage extends javax.swing.JFrame {

    /**
     * Creates new form BookingPage
     */
    public BookingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        roomtype = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        roomnum = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer ID:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 110, 20);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(130, 10, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer Name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 60, 110, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(130, 60, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Address:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 110, 120, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(130, 110, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 160, 110, 20);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(130, 160, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Room Type:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 200, 110, 20);

        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Standard Suite", "Premium Suite", "Executive Suite", "Royal Suite" }));
        roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtypeActionPerformed(evt);
            }
        });
        jPanel2.add(roomtype);
        roomtype.setBounds(130, 200, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Room Number:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 240, 110, 20);

        roomnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        roomnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnumActionPerformed(evt);
            }
        });
        jPanel2.add(roomnum);
        roomnum.setBounds(130, 240, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Guest Number:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 320, 110, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Check In:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 280, 110, 20);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(130, 320, 190, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Check Out:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 360, 110, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Cost:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 410, 110, 20);

        jTextTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalActionPerformed(evt);
            }
        });
        jPanel2.add(jTextTotal);
        jTextTotal.setBounds(130, 410, 100, 30);

        jButton1.setBackground(new java.awt.Color(141, 108, 92));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 470, 100, 30);

        jButton4.setBackground(new java.awt.Color(141, 108, 92));
        jButton4.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton4.setText("DONE");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(233, 470, 110, 30);

        jButton5.setBackground(new java.awt.Color(141, 108, 92));
        jButton5.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(120, 470, 100, 30);

        jButton2.setBackground(new java.awt.Color(141, 108, 92));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CHECK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(250, 240, 73, 30);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(130, 280, 190, 30);
        jPanel2.add(jDateChooser2);
        jDateChooser2.setBounds(130, 360, 190, 30);

        jButton3.setBackground(new java.awt.Color(141, 108, 92));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("COST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(250, 410, 70, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/hotel5.jpeg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 350, 530);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 40, 350, 530);

        jPanel4.setBackground(new java.awt.Color(141, 108, 92));
        jPanel4.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(141, 108, 92));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus_ID", "Cus_Name", "Cus_No", "Room_No", "Check In", "Check Out", "Cost"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 650, 530);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(350, 40, 650, 530);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ShamsHotels.ng");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 0, 170, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtypeActionPerformed
        // TODO add your handling code here:
        if (roomtype.getSelectedItem().toString().equals("Standard Suite"))
        {
            roomnum.removeAllItems();

            try
            {
                //Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");
                Connection con;
                Class.forName("com.mysql.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/shamshotel";
                String user = "root";
                String password = "";
                con = DriverManager.getConnection(url, user, password);
                PreparedStatement pst = null;
                Statement stmt = null;
                ResultSet rs = null;
                stmt = con.createStatement();
                String s = "Select Standard from roomtype where Type_ID = ?";
                int i = 1;
                while(i<=6)
                {
                    pst = con.prepareStatement(s);
                    pst.setInt(1, i);
                    rs=pst.executeQuery();
                    if(rs.next()){
                        roomnum.addItem(rs.getString("Standard"));
                        i++;
                    }
                }

                //int qexecute=stmt.executeUpdate(query);
                //JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully made");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (roomtype.getSelectedItem().toString().equals("Premium Suite"))
        {
            roomnum.removeAllItems();

            try
            {
                //Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");
                Connection con;
                Class.forName("com.mysql.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/shamshotel";
                String user = "root";
                String password = "";
                con = DriverManager.getConnection(url, user, password);
                PreparedStatement pst = null;
                Statement stmt = null;
                ResultSet rs = null;
                stmt = con.createStatement();
                String s = "Select Premium from roomtype";
                pst = con.prepareStatement(s);
                rs=pst.executeQuery();
                while(rs.next())
                {
                    roomnum.addItem(rs.getString(1));
                }

                //int qexecute=stmt.executeUpdate(query);
                //JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully made");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (roomtype.getSelectedItem().toString().equals("Executive Suite"))
        {
            roomnum.removeAllItems();

            try
            {
                //Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");
                Connection con;
                Class.forName("com.mysql.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/shamshotel";
                String user = "root";
                String password = "";
                con = DriverManager.getConnection(url, user, password);
                PreparedStatement pst = null;
                Statement stmt = null;
                ResultSet rs = null;
                stmt = con.createStatement();
                String s = "Select Executive from roomtype";
                pst = con.prepareStatement(s);
                rs=pst.executeQuery();
                while(rs.next())
                {
                    roomnum.addItem(rs.getString(1));
                }

                //int qexecute=stmt.executeUpdate(query);
                //JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully made");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (roomtype.getSelectedItem().toString().equals("Royal Suite"))
        {
            roomnum.removeAllItems();

            try
            {
                //Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");
                Connection con;
                Class.forName("com.mysql.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/shamshotel";
                String user = "root";
                String password = "";
                con = DriverManager.getConnection(url, user, password);
                PreparedStatement pst = null;
                Statement stmt = null;
                ResultSet rs = null;
                stmt = con.createStatement();
                String s = "Select Royal from roomtype";
                pst = con.prepareStatement(s);
                rs=pst.executeQuery();
                while(rs.next())
                {
                    roomnum.addItem(rs.getString(1));
                }

                //int qexecute=stmt.executeUpdate(query);
                //JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully made");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_roomtypeActionPerformed

    private void roomnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnumActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Cus_ID, Cus_Name, Address, Phone_No, Room_Type, Room_No, Check_In, Guest_No, Check_Out, Total_Cost;
        Cus_ID = jTextField2.getText();
        Cus_Name = jTextField3.getText();
        Address = jTextField1.getText();
        Phone_No = jTextField5.getText();
        Room_Type = (String) roomtype.getSelectedItem();
        Room_No = (String) roomnum.getSelectedItem();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Check_In = sdf.format(jDateChooser1.getDate());
        Guest_No = jTextField9.getText();
        Check_Out= sdf.format(jDateChooser2.getDate());
        Total_Cost = jTextTotal.getText();

        try{
            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/shamshotel";
            String user = "root";
            String password = "";
            con = DriverManager.getConnection(url, user, password);
            Statement stmt = null; stmt = con.createStatement();
            String query="INSERT INTO Customer_Table(Cus_ID, Cus_Name, Address, Phone_No, Room_Type, Room_No, Check_In, Guest_No, Check_Out, Total_Cost) "
            + "VALUES('"+Cus_ID+"', '"+Cus_Name+"', '"+Address+"', '"+Phone_No+"', '"+Room_Type+"', '"+Room_No+"', '"+Check_In+"', '"+Guest_No+"', '"+Check_Out+"', '"+Total_Cost+"');";
            stmt.executeUpdate(query);

            String query2="INSERT INTO booking_table(Cus_ID, Cus_Name, Address, Phone_No, Room_Type, Room_No, Check_In, Guest_No, Check_Out, Total_Cost) "
            + "VALUES('"+Cus_ID+"', '"+Cus_Name+"', '"+Address+"', '"+Phone_No+"', '"+Room_Type+"', '"+Room_No+"', '"+Check_In+"', '"+Guest_No+"', '"+Check_Out+"', '"+Total_Cost+"');";
            stmt.executeUpdate(query2);

            JOptionPane.showMessageDialog(this, "Your booking has been made");

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        WelcomePage wlcp = new WelcomePage();
        this.dispose();
        wlcp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField1.setText(null);
        jTextField5.setText(null);
        roomtype.setSelectedIndex(0);
        roomnum.setSelectedIndex(0);
        jDateChooser1.setDate(null);
        jTextField9.setText(null);
        jDateChooser2.setDate(null);
        jTextTotal.setText(null);
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            //Connection con = null;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/shamshotel";
            String user = "root";
            String password = "";
            con = DriverManager.getConnection(url, user, password);
            PreparedStatement pst = null;
            ResultSet rs = null;
            String s = "Select * from customer_table where Room_No = ?";

            pst = con.prepareStatement(s);
            pst.setString(1, String.valueOf(roomnum.getSelectedItem()));
            rs=pst.executeQuery();
            if (rs.next()){
                JOptionPane.showMessageDialog(this, "Room taken!");
            }else{
                String contain = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
                Random dig = new Random();
                StringBuilder sb = new StringBuilder(6);
                for(int i=0; i<6; i++)
                {
                    sb.append(contain.charAt(dig.nextInt(contain.length())));
                }
                String random = sb.toString();
                jTextField2.setText(random);

                jButton1.setEnabled(true);
                jButton3.setEnabled(true);
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //String str = new String();
        int StandardRoom = 9000;
        int PremiumRoom = 12000;
        int ExecutiveRoom = 20000;
        int RoyalRoom = 30000;

        SimpleDateFormat format = new SimpleDateFormat ("dd-mm-yyyy");
        Date Check_In = null;
        Date Check_Out = null;

        try{
            Check_Out = format.parse(format.format(jDateChooser2.getDate()));
            Check_In = format.parse(format.format(jDateChooser1.getDate()));
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        long Checkdiff = Check_Out.getTime() - Check_In.getTime();
        int Daysdiff = (int) (Checkdiff /1000/60/60/24);

        if(roomtype.getSelectedItem().equals("Standard Suite"))
        {
            jTextTotal.setText(Integer.toString(Daysdiff * StandardRoom));

            double st = Double.parseDouble(jTextTotal.getText());
            st=(st );
            String total = String.format(("# %.2f"), st);
            jTextTotal.setText(total);
        }
        if(roomtype.getSelectedItem().equals("Premium Suite"))
        {
            jTextTotal.setText(Integer.toString(Daysdiff * PremiumRoom));

            double st = Double.parseDouble(jTextTotal.getText());
            st=(st );
            String total = String.format(("# %.2f"), st);
            jTextTotal.setText(total);
        }
        if(roomtype.getSelectedItem().equals("Executive Suite"))
        {
            jTextTotal.setText(Integer.toString(Daysdiff * ExecutiveRoom));

            double st = Double.parseDouble(jTextTotal.getText());
            st=(st );
            String total = String.format(("# %.2f"), st);
            jTextTotal.setText(total);
        }
        if(roomtype.getSelectedItem().equals("Royal Suite"))
        {
            jTextTotal.setText(Integer.toString(Daysdiff * RoyalRoom));

            double st = Double.parseDouble(jTextTotal.getText());
            st=(st );
            String total = String.format(("# %.2f"), st);
            jTextTotal.setText(total);
        }
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{

            jTextField2.getText(),
            jTextField3.getText(),
            jTextField5.getText(),
            roomnum.getSelectedItem(),
            jDateChooser1.getDate(),
            jDateChooser2.getDate(),
            jTextTotal.getText(),
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String searchQuery = "Select Cus_ID, Cus_Name, Phone_No, Room_No, Check_In, Check_Out, Total_Cost from customer_table";
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con;
            ResultSet rs = null;
            String url = "jdbc:mysql://localhost:3306/shamshotel";        
            String user = "root";
            String password = "";
            PreparedStatement preparedStatement;
            con = DriverManager.getConnection(url, user, password);
       
       preparedStatement = (PreparedStatement) con.prepareStatement(searchQuery);
       
       rs = preparedStatement.executeQuery();
       
       jTable2.setModel(DbUtils.resultSetToTableModel(rs));
       
       }catch(ClassNotFoundException ce){
           JOptionPane.showMessageDialog(this, "Database Not Found", "Database Error",JOptionPane.ERROR_MESSAGE);
       }catch(SQLException se){
           JOptionPane.showMessageDialog(this,"Message: "+ se.getMessage() + "\nCode: " + se.getErrorCode() + "\nState Code " + se.getSQLState(), "Table Error!", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_formWindowActivated
    private JFrame frame1;private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JComboBox<String> roomnum;
    private javax.swing.JComboBox<String> roomtype;
    // End of variables declaration//GEN-END:variables
}
