/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Shams
 */
public class Create_Account extends javax.swing.JFrame {

    /**
     * Creates new form Create_Account
     */
    public Create_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        usertype = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bknwbtn = new javax.swing.JButton();
        rstrntbtn = new javax.swing.JButton();
        edtdtbtn = new javax.swing.JButton();
        hsekpnbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        homebtn1 = new javax.swing.JButton();
        admnlginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(141, 108, 92));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("lOGIN_ID");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 50, 130, 30);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(300, 50, 290, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FULL NAME");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(60, 380, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(50, 130, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONFIRM PASSWORD");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(40, 210, 170, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3);
        jTextField3.setBounds(300, 380, 290, 30);
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(300, 130, 290, 30);
        jPanel4.add(jPasswordField2);
        jPasswordField2.setBounds(300, 210, 290, 30);

        jButton2.setBackground(new java.awt.Color(141, 108, 92));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CLEAR FIELDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(440, 450, 140, 40);

        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Staff" }));
        jPanel4.add(usertype);
        usertype.setBounds(300, 300, 200, 40);

        jButton3.setBackground(new java.awt.Color(141, 108, 92));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("CONFIRM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(240, 450, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SELECT USER TYPE");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(50, 300, 150, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/cover2.jpeg"))); // NOI18N
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 0, 710, 530);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(290, 40, 710, 530);

        jPanel6.setBackground(new java.awt.Color(0, 51, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ShamsHotels.ng");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 0, 170, 40);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 1000, 40);

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));

        bknwbtn.setBackground(new java.awt.Color(141, 108, 92));
        bknwbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        bknwbtn.setText("book now");
        bknwbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bknwbtnActionPerformed(evt);
            }
        });

        rstrntbtn.setBackground(new java.awt.Color(141, 108, 92));
        rstrntbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        rstrntbtn.setText("view Customer Records");
        rstrntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstrntbtnActionPerformed(evt);
            }
        });

        edtdtbtn.setBackground(new java.awt.Color(141, 108, 92));
        edtdtbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edtdtbtn.setText("view laundry records");
        edtdtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtdtbtnActionPerformed(evt);
            }
        });

        hsekpnbtn.setBackground(new java.awt.Color(141, 108, 92));
        hsekpnbtn.setFont(new java.awt.Font("Algerian", 1, 17)); // NOI18N
        hsekpnbtn.setText("view restaurant records");
        hsekpnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsekpnbtnActionPerformed(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(141, 108, 92));
        logoutbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        logoutbtn.setText("Log out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        homebtn1.setBackground(new java.awt.Color(141, 108, 92));
        homebtn1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        homebtn1.setText("home");
        homebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtn1ActionPerformed(evt);
            }
        });

        admnlginbtn.setBackground(new java.awt.Color(141, 108, 92));
        admnlginbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        admnlginbtn.setText("register admin");
        admnlginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admnlginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bknwbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rstrntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hsekpnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admnlginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(edtdtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(admnlginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(homebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bknwbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(rstrntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(hsekpnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(edtdtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 40, 290, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(null);
        jTextField3.setText(null);
        jPasswordField2.setText(null);
        jPasswordField2.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Login_ID, Password, Confirm_Pass, User_Type, Name;
        Login_ID = jTextField2.getText();
        Password = jPasswordField1.getText();
        Confirm_Pass = jPasswordField2.getText();
        User_Type = (String) usertype.getSelectedItem();
        Name = jTextField3.getText();

        String pass = new String(jPasswordField1.getPassword());
        String repass = new String(jPasswordField2.getPassword());
        try {
            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/shamshotel";
            String user = "root";
            String password = "";
            con = DriverManager.getConnection(url, user, password);
            Statement stmt;
            PreparedStatement pds;
            pds = con.prepareStatement("INSERT INTO login_details values(?,?,?,?)");

            pds.setString(1, jTextField2.getText());
            pds.setString(2, pass);
//            pds.setString(3, repass);
            pds.setString(3, String.valueOf(usertype.getSelectedItem()));
            pds.setString(4, jTextField3.getText());
//
//            if (pass.equals(repass))   
//            {
//                pds.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Created Successfully");
//                logIn lgn = new logIn();
//                this.dispose();
//                lgn.setVisible(true);
//            } else {
//                JOptionPane.showMessageDialog(this, "Password Fields do not match");
//            }
             if(usertype.getSelectedIndex()==0){
                 JOptionPane.showMessageDialog(this, "Select User Type"); 
             }
             else if (pass.equals(repass)){
                  pds.executeUpdate();
                JOptionPane.showMessageDialog(this, "Created Successfully");
                logIn lgn = new logIn();
                this.dispose();
                lgn.setVisible(true);
             }else {
                JOptionPane.showMessageDialog(this, "Password Fields do not match");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void bknwbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bknwbtnActionPerformed
        AdminBookingPage abkn = new AdminBookingPage();
        this.dispose();
        abkn.setVisible(true);
        abkn.jButton1.setEnabled(false);
    }//GEN-LAST:event_bknwbtnActionPerformed

    private void rstrntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstrntbtnActionPerformed
        AdminCustomerRec adrec = new AdminCustomerRec();
        this.dispose();
        adrec.setVisible(true);
    }//GEN-LAST:event_rstrntbtnActionPerformed

    private void edtdtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtdtbtnActionPerformed
        AdminLaundryRec alrec = new AdminLaundryRec();
        this.dispose();
        alrec.setVisible(true);
    }//GEN-LAST:event_edtdtbtnActionPerformed

    private void hsekpnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsekpnbtnActionPerformed
        AdminRestaurantRec alrec = new AdminRestaurantRec();
        this.dispose();
        alrec.setVisible(true);
    }//GEN-LAST:event_hsekpnbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        logIn lgn = new logIn();
        this.dispose();
        lgn.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtn1ActionPerformed
        // TODO add your handling code here:
        AdminWelcomePage awlcp = new AdminWelcomePage();
        this.dispose();
        awlcp.setVisible(true);
    }//GEN-LAST:event_homebtn1ActionPerformed

    private void admnlginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admnlginbtnActionPerformed
        // TODO add your handling code here:
        Create_Account cracct = new Create_Account();
        this.dispose();
        cracct.setVisible(true);
    }//GEN-LAST:event_admnlginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admnlginbtn;
    private javax.swing.JButton bknwbtn;
    private javax.swing.JButton edtdtbtn;
    private javax.swing.JButton homebtn1;
    private javax.swing.JButton hsekpnbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton rstrntbtn;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables
}
