/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Shams
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bknwbtn = new javax.swing.JButton();
        rstrntbtn = new javax.swing.JButton();
        edtdtbtn = new javax.swing.JButton();
        hsekpnbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        homebtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(141, 108, 92));
        jPanel4.setLayout(null);

        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField);
        jTextField.setBounds(240, 20, 280, 50);

        jButton1.setBackground(new java.awt.Color(141, 108, 92));
        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(580, 30, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CUSTOMER ID");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(50, 30, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER NAME");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 90, 130, 30);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(300, 90, 290, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER ADDRESS");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(50, 130, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTACT NUMBER");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(50, 170, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ROOM TYPE");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(50, 210, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ROOM NUMBER");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(50, 250, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CHECK IN");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(50, 290, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GUEST NUMBER");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(50, 330, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CHECK OUT");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(50, 370, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TOTAL COST");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(50, 410, 110, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3);
        jTextField3.setBounds(300, 130, 290, 30);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(300, 170, 290, 30);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(300, 210, 290, 30);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(300, 250, 290, 30);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(300, 290, 290, 30);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(300, 330, 290, 30);
        jPanel4.add(jTextField9);
        jTextField9.setBounds(300, 370, 290, 30);
        jPanel4.add(jTextField10);
        jTextField10.setBounds(300, 410, 290, 30);

        jButton2.setBackground(new java.awt.Color(141, 108, 92));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CLEAR FIELDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(300, 470, 140, 40);

        jButton3.setBackground(new java.awt.Color(141, 108, 92));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("MODIFY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(140, 470, 110, 40);

        jButton6.setBackground(new java.awt.Color(141, 108, 92));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("DONE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(480, 470, 120, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/cover2.jpeg"))); // NOI18N
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 0, 710, 530);

        jLabel4.setText("jLabel4");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(50, 40, 34, 14);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(290, 40, 710, 530);

        jPanel6.setBackground(new java.awt.Color(0, 51, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel6.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ShamsHotels.ng");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 0, 170, 40);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 1000, 40);

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));

        bknwbtn.setBackground(new java.awt.Color(141, 108, 92));
        bknwbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        bknwbtn.setText("book now");
        bknwbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bknwbtnActionPerformed(evt);
            }
        });

        rstrntbtn.setBackground(new java.awt.Color(141, 108, 92));
        rstrntbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        rstrntbtn.setText("restaurant");
        rstrntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstrntbtnActionPerformed(evt);
            }
        });

        edtdtbtn.setBackground(new java.awt.Color(141, 108, 92));
        edtdtbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edtdtbtn.setText("edit details");
        edtdtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtdtbtnActionPerformed(evt);
            }
        });

        hsekpnbtn.setBackground(new java.awt.Color(141, 108, 92));
        hsekpnbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        hsekpnbtn.setText("LAUNDRY");
        hsekpnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsekpnbtnActionPerformed(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(141, 108, 92));
        logoutbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        logoutbtn.setText("Log out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        homebtn1.setBackground(new java.awt.Color(141, 108, 92));
        homebtn1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        homebtn1.setText("home");
        homebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bknwbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rstrntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hsekpnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(edtdtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(homebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(bknwbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(rstrntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(hsekpnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(edtdtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 40, 290, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/shamshotel";
            String user = "root";
            String password = "";
            con = DriverManager.getConnection(url, user, password);
            Statement stmt = null;
            stmt = con.createStatement();
            ResultSet rs = null;
            String q2 = "Select * from customer_table where Cus_ID=" + "'" + jTextField.getText() + "'" + " limit 1;";
            rs = stmt.executeQuery(q2);
            if (rs.next()) {
                jButton1.setEnabled(true);
                jTextField2.setText(rs.getString("Cus_Name"));
                jTextField3.setText(rs.getString("Address"));
                jTextField4.setText(rs.getString("Phone_No"));
                jTextField5.setText(rs.getString("Room_Type"));
                jTextField6.setText(rs.getString("Room_No"));
                jTextField7.setText(rs.getString("Check_In"));
                jTextField8.setText(rs.getString("Guest_No"));
                jTextField9.setText(rs.getString("Check_Out"));
                jTextField10.setText(rs.getString("Total_Cost"));
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Reference Number!");
                //jButton1.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Cus_Name, Address, Phone_No, Room_Type, Room_No, Check_In, Guest_No, Check_Out, Total_Cost;

        Cus_Name = jTextField2.getText();
        Address = jTextField3.getText();
        Phone_No = jTextField4.getText();
        Room_Type = jTextField5.getText();
        Room_No = jTextField6.getText();
        Check_In = jTextField7.getText();
        Guest_No = jTextField8.getText();
        Check_Out = jTextField9.getText();
        Total_Cost = jTextField10.getText();
        try {
            String search = jTextField.getText();
            Connection con;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/shamshotel";
            String user = "root";
            String password = "";
            con = DriverManager.getConnection(url, user, password);
            Statement stmt = null;
            stmt = con.createStatement();
            String query = "update customer_table set Cus_Name = '" + Cus_Name + "', Address = '" + Address + "', Phone_No = '" + Phone_No + "', Room_Type = '" + Room_Type + "', Room_No = '" + Room_No + "', Check_In = '" + Check_In + "', Guest_No= '" + Guest_No + "', Check_Out = '" + Check_Out + "', Total_Cost = '" + Total_Cost + "' where Cus_ID=" + "'" + jTextField.getText() + "'" + " limit 1;";
            String query2 = "update booking_table set Cus_Name = '" + Cus_Name + "', Address = '" + Address + "', Phone_No = '" + Phone_No + "', Room_Type = '" + Room_Type + "', Room_No = '" + Room_No + "', Check_In = '" + Check_In + "', Guest_No= '" + Guest_No + "', Check_Out = '" + Check_Out + "', Total_Cost = '" + Total_Cost + "' where Cus_ID=" + "'" + jTextField.getText() + "'" + " limit 1;";
            if (jTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please input Customer ID");
            } else {
                int qexecute = stmt.executeUpdate(query);
                int fexecute = stmt.executeUpdate(query2);
                JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully made");
                jTextField.setText(null);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField4.setText(null);
                jTextField5.setText(null);
                jTextField6.setText(null);
                jTextField7.setText(null);
                jTextField8.setText(null);
                jTextField9.setText(null);
                jTextField10.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void bknwbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bknwbtnActionPerformed
        BookingPage bkn = new BookingPage();
        this.dispose();
        bkn.setVisible(true);
        bkn.jButton1.setEnabled(false);
    }//GEN-LAST:event_bknwbtnActionPerformed

    private void rstrntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstrntbtnActionPerformed
        RestaurantPage restp = new RestaurantPage();
        this.dispose();
        restp.setVisible(true);
    }//GEN-LAST:event_rstrntbtnActionPerformed

    private void edtdtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtdtbtnActionPerformed
        EditDetails edtd = new EditDetails();
        this.dispose();
        edtd.setVisible(true);
    }//GEN-LAST:event_edtdtbtnActionPerformed

    private void hsekpnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsekpnbtnActionPerformed
        Laundry lunp = new Laundry();
        this.dispose();
        lunp.setVisible(true);
    }//GEN-LAST:event_hsekpnbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        logIn lgn = new logIn();
        this.dispose();
        lgn.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtn1ActionPerformed
        // TODO add your handling code here:
        WelcomePage wlcp = new WelcomePage();
        this.dispose();
        wlcp.setVisible(true);
    }//GEN-LAST:event_homebtn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EditDetails edtd = new EditDetails();
        this.dispose();
        edtd.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bknwbtn;
    private javax.swing.JButton edtdtbtn;
    private javax.swing.JButton homebtn1;
    private javax.swing.JButton hsekpnbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton rstrntbtn;
    // End of variables declaration//GEN-END:variables
}
