/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import javax.swing.JFrame;

/**
 *
 * @author Shams
 */
public class EditDetails extends javax.swing.JFrame {

    /**
     * Creates new form EditDetails
     */
    public EditDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updtrcstbtn = new javax.swing.JButton();
        updtmcstbtn = new javax.swing.JButton();
        updtrtcstbtn = new javax.swing.JButton();
        updtrtcstbtn1 = new javax.swing.JButton();
        updtrtcstbtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bknwbtn = new javax.swing.JButton();
        rstrntbtn = new javax.swing.JButton();
        edtdtbtn = new javax.swing.JButton();
        hsekpnbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        homebtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(null);

        updtrcstbtn.setBackground(new java.awt.Color(141, 108, 92));
        updtrcstbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        updtrcstbtn.setText("edit");
        updtrcstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtrcstbtnActionPerformed(evt);
            }
        });
        jPanel2.add(updtrcstbtn);
        updtrcstbtn.setBounds(190, 40, 364, 34);

        updtmcstbtn.setBackground(new java.awt.Color(141, 108, 92));
        updtmcstbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        updtmcstbtn.setText("delete");
        updtmcstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtmcstbtnActionPerformed(evt);
            }
        });
        jPanel2.add(updtmcstbtn);
        updtmcstbtn.setBounds(190, 140, 364, 34);

        updtrtcstbtn.setBackground(new java.awt.Color(141, 108, 92));
        updtrtcstbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        updtrtcstbtn.setText("view laundry record");
        updtrtcstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtrtcstbtnActionPerformed(evt);
            }
        });
        jPanel2.add(updtrtcstbtn);
        updtrtcstbtn.setBounds(190, 460, 364, 34);

        updtrtcstbtn1.setBackground(new java.awt.Color(141, 108, 92));
        updtrtcstbtn1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        updtrtcstbtn1.setText("view hotel record");
        updtrtcstbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtrtcstbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(updtrtcstbtn1);
        updtrtcstbtn1.setBounds(190, 250, 364, 34);

        updtrtcstbtn2.setBackground(new java.awt.Color(141, 108, 92));
        updtrtcstbtn2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        updtrtcstbtn2.setText("view restaurant record");
        updtrtcstbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtrtcstbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(updtrtcstbtn2);
        updtrtcstbtn2.setBounds(190, 360, 364, 34);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/cover2.jpeg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 530);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 40, 710, 530);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ShamsHotels.ng");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 0, 170, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 40);

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));

        bknwbtn.setBackground(new java.awt.Color(141, 108, 92));
        bknwbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        bknwbtn.setText("book now");
        bknwbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bknwbtnActionPerformed(evt);
            }
        });

        rstrntbtn.setBackground(new java.awt.Color(141, 108, 92));
        rstrntbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        rstrntbtn.setText("restaurant");
        rstrntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstrntbtnActionPerformed(evt);
            }
        });

        edtdtbtn.setBackground(new java.awt.Color(141, 108, 92));
        edtdtbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edtdtbtn.setText("edit details");
        edtdtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtdtbtnActionPerformed(evt);
            }
        });

        hsekpnbtn.setBackground(new java.awt.Color(141, 108, 92));
        hsekpnbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        hsekpnbtn.setText("LAUNDRY");
        hsekpnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsekpnbtnActionPerformed(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(141, 108, 92));
        logoutbtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        logoutbtn.setText("Log out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        homebtn1.setBackground(new java.awt.Color(141, 108, 92));
        homebtn1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        homebtn1.setText("home");
        homebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bknwbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rstrntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hsekpnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(edtdtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(homebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(bknwbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(rstrntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(hsekpnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(edtdtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 40, 290, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updtrcstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtrcstbtnActionPerformed
        // TODO add your handling code here:
        Edit edt = new Edit();
        this.dispose();
        edt.setVisible(true);
    }//GEN-LAST:event_updtrcstbtnActionPerformed

    private void updtmcstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtmcstbtnActionPerformed
        // TODO add your handling code here:
        Delete dl = new Delete();
        this.dispose();
        dl.setVisible(true);
    }//GEN-LAST:event_updtmcstbtnActionPerformed

    private void updtrtcstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtrtcstbtnActionPerformed
        // TODO add your handling code here:
        LaundryRec laurec = new LaundryRec();
        this.dispose();
        laurec.setVisible(true);
    }//GEN-LAST:event_updtrtcstbtnActionPerformed

    private void updtrtcstbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtrtcstbtn1ActionPerformed
        // TODO add your handling code here:
        CustomerRec cusrec = new CustomerRec();
        this.dispose();
        cusrec.setVisible(true);
    }//GEN-LAST:event_updtrtcstbtn1ActionPerformed

    private void updtrtcstbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtrtcstbtn2ActionPerformed
        // TODO add your handling code here:
        RestaurantRec resrec = new RestaurantRec();
        this.dispose();
        resrec.setVisible(true);
    }//GEN-LAST:event_updtrtcstbtn2ActionPerformed

    private void bknwbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bknwbtnActionPerformed
        BookingPage bkn = new BookingPage ();
        this.dispose();
        bkn.setVisible(true);
        bkn.jButton1.setEnabled(false);
    }//GEN-LAST:event_bknwbtnActionPerformed

    private void rstrntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstrntbtnActionPerformed
        RestaurantPage restp = new RestaurantPage();
        this.dispose();
        restp.setVisible(true);
    }//GEN-LAST:event_rstrntbtnActionPerformed

    private void edtdtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtdtbtnActionPerformed
        EditDetails edtd = new EditDetails();
        this.dispose();
        edtd.setVisible(true);
    }//GEN-LAST:event_edtdtbtnActionPerformed

    private void hsekpnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsekpnbtnActionPerformed
        Laundry lunp = new Laundry();
        this.dispose();
        lunp.setVisible(true);
    }//GEN-LAST:event_hsekpnbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        logIn lgn = new logIn();
        this.dispose();
        lgn.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtn1ActionPerformed
        // TODO add your handling code here:
        WelcomePage wlcp = new WelcomePage();
        this.dispose();
        wlcp.setVisible(true);
    }//GEN-LAST:event_homebtn1ActionPerformed
    private JFrame frame1;private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bknwbtn;
    private javax.swing.JButton edtdtbtn;
    private javax.swing.JButton homebtn1;
    private javax.swing.JButton hsekpnbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton rstrntbtn;
    private javax.swing.JButton updtmcstbtn;
    private javax.swing.JButton updtrcstbtn;
    private javax.swing.JButton updtrtcstbtn;
    private javax.swing.JButton updtrtcstbtn1;
    private javax.swing.JButton updtrtcstbtn2;
    // End of variables declaration//GEN-END:variables
}
