/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Shams
 */
public class logIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public logIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        loginbtn1 = new javax.swing.JButton();
        loginbtn2 = new javax.swing.JButton();
        usertype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(null);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(120, 100, 160, 40);

        jLabel8.setFont(new java.awt.Font("Algerian", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASSWORD;");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 170, 90, 60);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(120, 180, 160, 40);

        jLabel9.setFont(new java.awt.Font("Algerian", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USER-ID:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 90, 90, 60);

        loginbtn1.setBackground(new java.awt.Color(141, 108, 92));
        loginbtn1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        loginbtn1.setText("QUIT");
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(loginbtn1);
        loginbtn1.setBounds(160, 340, 110, 40);

        loginbtn2.setBackground(new java.awt.Color(141, 108, 92));
        loginbtn2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        loginbtn2.setText("Login");
        loginbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(loginbtn2);
        loginbtn2.setBounds(20, 340, 110, 40);

        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Staff" }));
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        jPanel2.add(usertype);
        usertype.setBounds(120, 260, 110, 30);

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER TYPE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 260, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 40, 290, 530);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ShamsHotels.ng");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 0, 170, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 40);

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("At ShamsHotels.ng your comfort ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 110, 490, 40);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("is our main priority");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 210, 310, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/pictures/cover2.jpeg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 40, 710, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame1;private JFrame frame;
    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtn1ActionPerformed

    private void loginbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn2ActionPerformed
        // TODO add your handling code here:
      try{ 
        Connection con;
        Class.forName("com.mysql.jdbc.Driver"); 
        String url = "jdbc:mysql://localhost:3306/shamshotel";
        String user = "root";
        String password = "";
        con = DriverManager.getConnection(url, user, password);
            Statement stmt; 
            //stmt = con.createStatement(q2);
            ResultSet rs;
            PreparedStatement ps;
        ps = con.prepareStatement("Select 'Login_ID', 'Password', 'User_Type' from Login_Details where Login_ID = ? and Password = ? and User_Type = ?");
        ps.setString(1,  jTextField1.getText());
        ps.setString(2, String.valueOf(jPasswordField1.getPassword()));
        ps.setString(3, String.valueOf(usertype.getSelectedItem()));
        rs=ps.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(this, "Log In Successful and you are logged in as "+String.valueOf(usertype.getSelectedItem()));
        if(usertype.getSelectedIndex()==1){
            AdminWelcomePage awlcp = new AdminWelcomePage();
            this.dispose();
            awlcp.setVisible(true); 
        }
        else if(usertype.getSelectedIndex()==2){
            WelcomePage wpg = new WelcomePage();
            wpg.setVisible(true);
            this.dispose();    
        }
        else{
            JOptionPane.showMessageDialog(this, "Select User Type");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid Username, Password or User Type");
        }
        
        }
      
         catch (Exception e) 
         { 
             JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_loginbtn2ActionPerformed

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JButton loginbtn2;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables
}
